# -*- coding: utf-8 -*-
"""stock_investment_assistance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CYIFPs0UYc8GgcN_SSXOALthaIk_eUEI

# 1. Environment&Import
"""
import os.path
import numpy as np
import pandas as pd
import yfinance as yf
import FinanceDataReader as fdr
import matplotlib.pyplot as plt
from tqdm import tqdm

startdate='2022-01-01'
enddate='2023-02-04'

from portfolio import portfolio
from indexSearch import indexSearch
from tickerSearch import tickerSearch
from financialCompare import implement

## 1. Create portfolio from csv
portfolio().implement(startdate,enddate)

# 2. Search Tickers
# tickerSearched=tickerSearch('NYSE','수도 유틸리티').download(0.2)
# print(tickerSearched)

# # 3. Compare Financials
# tickerDict={
#     'SEARCH':tickerSearched.index,
#     'WATCH':['CLFD','STEM','GOOG','EQNR','ON','ONTO','FLEX','PERI','META','IMKTA','CALM','CLH','CRAI']
# }

# implement(tickerDict,'WATCH')
