# -*- coding: utf-8 -*-
"""stock_investment_assistance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CYIFPs0UYc8GgcN_SSXOALthaIk_eUEI

# 1. Environment&Import
"""

start='2023-01-01'
end='2023-06-20'

import usia

"""1. Create portfolio from csv"""
path="data\private.csv"
portfoilo=usia.portfolio(path,start,end)
portfoilo.implement()

"""2. Search Tickers"""
searched=usia.tickerSearch('NASDAQ','헬스케어 장비 및 용품').download(start,end,filter_percent=1)
print(searched)

"""3. Compare Financials"""
tickers=searched.index
watchlist=['PANW','AMZN','RCM','STEM']
result=usia.financialCompare(watchlist).keyFinancialTable()
print(result)

